version: "3"
name: "microservicios"

services:
  nats-server:
    image: nats:latest
  client-gateway:
    image: client-gateway-prod
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  auth-ms:
    image: auth-ms-prod
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  products-ms:
    image: products-ms-prod
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  payments-ms:
    image: payments-ms-prod
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
